greenroom/apps/django_facebook_patched/urls.py
from django.conf.urls.defaults import patterns, url
from greenroom.apps.django_facebook_patched import settings as facebook_settings

urlpatterns = patterns('greenroom.apps.django_facebook_patched.views',
   url(r'^connect/$', 'connect', name='facebook_connect'),
   url(r'^image_upload/$', 'image_upload', name='facebook_image_upload'),
   url(r'^wall_post/$', 'wall_post', name='facebook_wall_post'),
   url(r'^canvas/$', 'canvas', name='facebook_canvas'),
)




#help autodiscovery a bit
from greenroom.apps.django_facebook_patched import admin

greenroom/urls.py
from django.conf import settings
from django.conf.urls import include, patterns, url

import greenroom.apps.feedback.views as feedback_views
import greenroom.apps.outfit.views as outfit_views
import greenroom.apps.www.views as www_views


urlpatterns = patterns('',
    # apps.www
    url(r'^$', www_views.home, name='www_home'),
    # apps.outfit
    url(r'^outfit/new$', outfit_views.new_outfit, name='outfit_new_outfit'),
    url(r'^outfit/list$', outfit_views.list_outfits, name='outfit_list_outfits'),
    url(r'^outfit/(?P<uuid>.{6})$', outfit_views.view_outfit, name='outfit_view_outfit'),
    url(r'^outfit/(?P<uuid>.{6})/request_feedback$', outfit_views.request_feedback, name='outfit_request_feedback'),
    # apps.feedback
    url(r'^outfit/feedback/(?P<uuid>.{6})$', feedback_views.give_feedback, name='outfit_give_feedback'),
    # django-facebook
    (r'^facebook/', include('greenroom.apps.django_facebook_patched.urls')),
    (r'^accounts/', include('greenroom.apps.django_facebook_patched.auth_urls')), #Don't add this line if you use django registration or userena for registration and auth.
)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.STATIC_ROOT,
        }),
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),
   )

greenroom/apps/feedback/models.py
import random
import string

from django.conf import settings
from django.core.urlresolvers import reverse
from django.db import models

from .helpers import retrieve_outfit


def generate_uuid():
    # return a 6-char string random of letters and digits e.g. 4Gcr92
    return ''.join(random.choice(string.ascii_letters + string.digits) for i in range(6))
    
class OutfitFeedback(models.Model):
    RATING_CHOICES = ((1,1), (2,2), (3,3), (4,4), (5,5))

    uuid = models.CharField(max_length=6, default=generate_uuid, editable=False, primary_key=True) # auto-generated
    outfit_pk = models.CharField(max_length=6) # fits the uuid of the outfit
    rating = models.IntegerField(max_length=1, choices=RATING_CHOICES, null=True, blank=True)
    requested_at = models.DateTimeField(auto_now_add=True, editable=False)
    answered_at = models.DateTimeField(editable=False, null=True, blank=True)

    emailed_to = models.EmailField()
    comment = models.TextField()

    @property
    def outfit(self):
        return retrieve_outfit(self.outfit_pk)

    @property
    def rating_doubled(self):
        return self.rating * 2
        
    @property
    def feedback_url(self):
        """Sharable URL for outfit feedback giving"""
        return settings.HOST + self.get_absolute_url()

    def get_absolute_url(self):
        return reverse('outfit_give_feedback', args=[self.uuid])

greenroom/apps/www/models.py
from django.db import models

# Create your models here.

greenroom/apps/www/views.py
from django.shortcuts import render

from .helpers import get_facebook_friends
        

def home(request):
    # user might be authenticated and logged in only via Facebook (no other auth possibility)
    fb_friends = get_facebook_friends(request) if request.user.is_authenticated() else []
    return render(request, 'home.html', {'fb_friends': fb_friends,
    	'outfits': request.user.outfit_set.all().order_by('-submitted_at') if request.user.is_authenticated() else []})
    				

greenroom/apps/www/templates/home.html
{% extends 'base.html' %}

{% block body %}
<div class="main-content">
	<div class="allwidth deco">
		<div class="container">
			{% if not user.is_authenticated %}

					<div class="logo">
						<img src="{{ STATIC_URL }}images/logo.png" alt="greenroom">
					</div>
			{% endif %}

<!-- 				<div class="span-10 offset-1">
					<div id="mirror">
			          <div id="result-img"></div>
			          <div id="mirror-inner"></div>
			          <div id="placeholder-pic">
			          	<p class="suggestions rotate-text">
			          		get yourself ready!
			          	</p>
						<div class="big-arrow"></div>
			          </div>
					  <div id="camera" class="hidden"></div>
           				<canvas id="canvas" height="240" width="320" class="hidden"></canvas>
					</div>
				</div> -->
			<div class="row">
				<div id="mirror">
		          	<div id="result-img" class="img-result max-width"></div>
		          	<div id="mirror-inner"></div>
	<!-- 			          	<div id="placeholder-pic"></div>
	-->				<div id="camera" class="hidden"></div>
	   				<canvas id="canvas" height="240" width="320" class="hidden"></canvas>
				</div>

				<div id="step-1" class=" step hidden">
					<div class="span-5 suggestions left-side">
						only your real friends can give you a trustable opinion
						<div class="big-arrow"></div>
					</div>

			        <div class="span-3">
			          <div class="button big" id="show-camera">Take picture <span class="action"></span></div>
			        </div>
			        <div class="span-3">
			          <div class="button big blue" id="uploader">Upload <span class="action"></span></div>
			        </div>
			        <div class="hidden offset-5" id="capture">
			          <div class="span-3">
			          	<div class="button big" id="capture-btn">Capture <span class="action"></span></div>
			          </div>
  			          <div class="span-3">
			          	<div class="button big red back" id="">Discard <span class="action"></span></div>
			          </div>
			        </div>
			        <div class="span-16">
			        	<p class="suggestions rotate-text center">
			          		get yourself ready!
			          	</p>
			        </div>
		      	</div>
<!-- 	  		     <div id="step-capture" class="row step hidden">
					<div id="mirror">
			          	<div id="result-img"></div>
			          	<div id="mirror-inner"></div>
			          	<div id="placeholder-pic"></div>
					  	<div id="camera" class="hidden"></div>
           				<canvas id="canvas" height="240" width="320" class="hidden"></canvas>
					</div>
			        <div class="span-4 offset-7">
			          <div class="button big" id="ok">Ask for feedback</div>
			        </div>
			        <div class="span-4">
			          <div class="button big red" id="back">Take another</div>
			        </div>
		      </div> -->
  		        <div id="step-2" class="row step hidden">
			        <div class="span-3 offset-5">
			          <div class="button big" id="ok">Ask for feedback <span class="action"></span></div>
			        </div>
			        <div class="span-3">
			          <div class="button big red back" id="">Take another</div>
			        </div>
		      	</div>

		      	<div id="step-3" class="step hidden ask-feedback-form">
			        <form id="form-ask" action="" method="post" class="">
			            {% csrf_token %}
			            <div class="span-6 offset-5">
			              <h3>Ask your friends</h3>
			              <textarea name="description" placeholder="My message"></textarea>
			              <ul>
			                <li class="email-icon"><input type="text" placeholder="nameofyourfriends@email.com" name="email_1" /> </li>
			                <li class="email-icon"><input type="text" placeholder="nameofyourfriends@email.com" name="email_2" /> </li>
			                <li class="email-icon"><input type="text" placeholder="nameofyourfriends@email.com" name="email_3" /> </li><a>add mail</a>
			              </ul>
			            <input class="button" type="submit" value="Ask feedback" />
			            </div>
				            <div class="">
				              <div class="span-16">
				              	<h3>or ask your friends on facebook</h3>
				              	{% if not user.is_authenticated %}
									<form id="fbconnect" action="{% url facebook_connect %}?facebook_login=1" method="post">
										<a class="zocial facebook" href="javascript:void(0);" style="font-size: 14px;" onclick="F.connect(this.parentNode);">Login with Facebook</a>
										<input type="hidden" value="{{ request.path }}" name="next" />
									</form>					
								{% endif %}	
							  </div>
							  <div class="row">
					            <div id="fb-friends" >
					              	{% for f in fb_friends %}
					                    <div class="fb-friend">
							                <img src='{{ f.pic_square }}' height="50" width="50" />
							                <input type="checkbox" name="email_fb_{{ forloop.counter }}" value='{{ f.username }}@facebook.com' /> {{ f.name }} <br />
					                  </div>
					              {% endfor %}
					            </div>
					           </div>
				          </div>
			        </form>
							<!-- </div> -->
				</div>
			</div>
		</div>
		{% if user.is_authenticated %}
		<div class="container">
			<div class="row">
				<div class="span-12">
					<h3>Your last outfits</h3>
						{% for o in outfits %}
						 <a href='{{ o.view_url }}'>
							<div class="span-3 outfit-image">
								<img src="{{ o.img.url }}" style="max-width: 200;" />
								<div>
									<div class="span-1">
										<ul>
											<li class="comments {% if not o.comment %}null{% endif %}">
												<span>{{ o.outfitfeedback_set.all|length }}</span>
											</li>
										</ul>
									</div>
									<div class="span-1 offset-2">
									</div>
									<!-- <a href='{{ o.view_url }}'>
										From {{ o.submitted_at|date:"H:i a" }}
										Average rating: {{ o.avg_rating|default:"no ratings yet" }}
									</a> -->
								</div>
							</div>
						</a>
						{% endfor %}
				</div>
				<div class="span-4">
					<h3>Last friends comments</h3>
				</div>
			</div>
			{% endif %}
		</div>
	</div>
</div>
{% endblock %}